regenerated configure
git-svn-id: https://svn.macports.org/repository/macports/trunk/base@2825 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2011,9 +2011,9 @@ echo "$as_me: WARNING: No dports tree found" >&2;}
 echo $ECHO_N "checking for ports config directory... $ECHO_C" >&6
 
 	if test "$prefix" != "NONE" ; then
-				portconfigdir="\${sysconfdir}/ports"
+				portconfigdir='${sysconfdir}/ports'
 	else
-				portconfigdir="/etc/ports"
+				portconfigdir='/etc/ports'
 	fi
 
 	echo "$as_me:2019: result: $portconfigdir" >&5
@@ -3818,7 +3818,10 @@ fi
 
 eval "prefix_expanded=$prefix"
 
+# do this twice, since there is a nested variable of
+# ${prefix} inside of ${sysconfdir}
 eval "PORTCONFIGDIR_EXPANDED=$PORTCONFIGDIR"
+eval "PORTCONFIGDIR_EXPANDED=$PORTCONFIGDIR_EXPANDED"
 
 eval "localstatedir_expanded=$localstatedir"
 
@@ -3826,7 +3829,7 @@ prefix=$oldprefix
 
 # Output
 
-ac_config_files="$ac_config_files Makefile Mk/dports.autoconf.mk doc/prefix.mtree doc/ports.conf"
+ac_config_files="$ac_config_files Makefile Mk/dports.autoconf.mk doc/prefix.mtree doc/ports.conf src/darwinports1.0/darwinports.tcl.out:src/darwinports1.0/darwinports.tcl"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -3907,7 +3910,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:3910: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:3913: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -4080,7 +4083,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:4083: error: ambiguous option: $1
+    { { echo "$as_me:4086: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -4099,7 +4102,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:4102: error: unrecognized option: $1
+  -*) { { echo "$as_me:4105: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -4138,8 +4141,9 @@ do
   "Mk/dports.autoconf.mk" ) CONFIG_FILES="$CONFIG_FILES Mk/dports.autoconf.mk" ;;
   "doc/prefix.mtree" ) CONFIG_FILES="$CONFIG_FILES doc/prefix.mtree" ;;
   "doc/ports.conf" ) CONFIG_FILES="$CONFIG_FILES doc/ports.conf" ;;
+  "src/darwinports1.0/darwinports.tcl.out" ) CONFIG_FILES="$CONFIG_FILES src/darwinports1.0/darwinports.tcl.out:src/darwinports1.0/darwinports.tcl" ;;
   "src/pextlib1.0/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS src/pextlib1.0/config.h" ;;
-  *) { { echo "$as_me:4142: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:4146: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4387,7 +4391,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4390: creating $ac_file" >&5
+    { echo "$as_me:4394: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4405,7 +4409,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4408: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4412: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4418,7 +4422,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4421: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4425: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4479,7 +4483,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:4482: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:4486: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -4490,7 +4494,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4493: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4497: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4503,7 +4507,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4506: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4510: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4620,7 +4624,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:4623: $ac_file is unchanged" >&5
+      { echo "$as_me:4627: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
