Regen
git-svn-id: https://svn.macports.org/repository/macports/trunk/base@7645 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2401,6 +2401,52 @@ fi
 
 
 
+	echo "$as_me:$LINENO: checking how to mark unused variables" >&5
+echo $ECHO_N "checking how to mark unused variables... $ECHO_C" >&6
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+int a __attribute__ ((unused));
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+cat >>confdefs.h <<\_ACEOF
+#define UNUSED __attribute__((unused))
+_ACEOF
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+cat >>confdefs.h <<\_ACEOF
+#define UNUSED
+_ACEOF
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+	echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6
+
+
+
+
+
 	# Extract the first word of "mtree", so it can be a program name with args.
 set dummy mtree; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -2579,7 +2625,6 @@ echo "${ECHO_T}$DSTGRP" >&6
 
 
 # Check for standard header files.
-
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
