Just warn if updating RUNUSR home dir fails
See: https://trac.macports.org/ticket/72676
(cherry picked from commit d1e4f0422f75be85a0c7a0c44701906cc138326e)

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -80,7 +80,11 @@ ifeq ($(DESTDIR),)
             if test "$$RUNUSR_UID" -gt 500 -a "$$RUNUSR_SHELL" = "/usr/bin/false" -a "$$RUNUSR_NAME" = "MacPorts" ; then \
                 if test "$$(${DSCL} -q . -read "/Users/${RUNUSR}" NFSHomeDirectory)" != "NFSHomeDirectory: ${localstatedir}/macports/home" ; then \
                     echo "Updating home directory location for user \"${RUNUSR}\"" ; \
-                    ${DSCL} -q . -create "/Users/${RUNUSR}" NFSHomeDirectory "${localstatedir}/macports/home" ; \
+                    if ! ${DSCL} -q . -create "/Users/${RUNUSR}" NFSHomeDirectory "${localstatedir}/macports/home" ; then \
+                        echo "Failed to update home directory!" ; \
+                        echo "Please ask the system administrator to manually run:" ; \
+                        echo "    ${DSCL} -q . -create \"/Users/${RUNUSR}\" NFSHomeDirectory \"${localstatedir}/macports/home\"" ; \
+                    fi ; \
                 fi ; \
             fi ; \
         else \
