Reword a warning printed to the installer log.
git-svn-id: https://svn.macports.org/repository/macports/branches/release_1_6/base@32848 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/portmgr/dmg/postflight b/portmgr/dmg/postflight
--- a/portmgr/dmg/postflight
+++ b/portmgr/dmg/postflight
@@ -93,7 +93,7 @@ function write_setting () {
             fi
             ;;
     esac
-    chown ${USER} ${HOME}/.${CONF_FILE} || echo "Unable to switch your ${HOME}/.${CONF_FILE} shell configuration file to your UID!"
+    chown ${USER} ${HOME}/.${CONF_FILE} || echo "Warning: unable to adapt permissions on your ${HOME}/.${CONF_FILE} shell configuration file!"
     echo -e "# Finished adapting your ${1} environment variable for use with MacPorts.\n" >> ${HOME}/.${CONF_FILE}
     echo "An appropriate ${1} variable has been added to your shell environment by the MacPorts installer."
 }
