Move the definition of the 'update_macports' command to the top of the script, so that it is found if we for some reason fail to determine the shell through the basename(1) command.
git-svn-id: https://svn.macports.org/repository/macports/branches/release_1_6/base@32632 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/portmgr/dmg/postflight b/portmgr/dmg/postflight
--- a/portmgr/dmg/postflight
+++ b/portmgr/dmg/postflight
@@ -32,6 +32,19 @@
 # $Id$
 
 
+# Command to update the MacPorts installation through "selfupdate":
+function update_macports {
+    export PATH=$BINPATH:$PATH
+    echo "Synchronizing the MacPorts installation with the project's rsync server..."
+    if ! port -v selfupdate; then 
+        echo "An attempt to synchronize your recent MacPorts installation with the project's rsync server failed!"
+        echo "Please run 'port -d selfupdate' manually to find out the cause of the error."
+    else
+        echo "Successful!"
+    fi
+}
+
+
 # Abstraction variables:
 PREFIX=/opt/local
 BINPATH=$PREFIX/bin
@@ -84,18 +97,6 @@ function write_setting () {
     esac
     chown $USER $HOME/.$CONF_FILE || echo "Unable to switch your $HOME/.$CONF_FILE shell configuration file to your UID!"
     echo -e "# Finished adapting your $1 environment variable for use with MacPorts.\n" >> $HOME/.$CONF_FILE
-}
-
-# Command to update the MacPorts installation through "selfupdate":
-function update_macports {
-    export PATH=$BINPATH:$PATH
-    echo "Synchronizing the MacPorts installation with the project's rsync server..."
-    if ! port -v selfupdate; then 
-        echo "An attempt to synchronize your recent MacPorts installation with the project's rsync server failed!"
-        echo "Please run 'port -d selfupdate' manually to find out the cause of the error."
-    else
-        echo "Successful!"
-    fi
 }
 
 
