updated tools
git-svn-id: https://svn.macports.org/repository/macports/branches/gsoc10-configfiles/tools@70232 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/tools/gsocswitchversion b/tools/gsocswitchversion
--- a/tools/gsocswitchversion
+++ b/tools/gsocswitchversion
@@ -1,13 +1,16 @@
 #!/bin/bash
 
-PORTPATH=$(port dir gsoc-dummy)
+PORTPATH=$(port dir gsocdummy 2>/dev/null)
+if [[ ! $PORTPATH ]]; then echo "Error: can't find gsoc-dummy port directory"; exit 1; fi 
 read _ revision <<< $(cat "$PORTPATH"/Portfile | grep revision)
-echo -n "Switching gsoc-dummy from revision "
+echo -n "Switching gsocdummy from revision "
+cd "$PORTPATH"
 if [[ $revision = 0 ]]; then
     echo "0 to 1"
-    sed -e 's,\(revision[ ]*\)0,\11,' Portfile >"$PORTPATH"/NewPortfile
+    sed -e 's,\(revision[ ]*\)0,\11,' Portfile >NewPortfile
 else
     echo "1 to 0"
-    sed -e 's,\(revision[ ]*\)1,\10,' Portfile >"$PORTPATH"/NewPortfile
+    sed -e 's,\(revision[ ]*\)1,\10,' Portfile >NewPortfile
 fi
-mv "$PORTPATH"/NewPortfile "$PORTPATH"/Portfile
+cp Portfile Portfile.backup
+mv NewPortfile Portfile
